### ISSUE TITLE
Add offline button 

### ISSUE THREAD

**Issue by Rocraft27** [SolDev69/SolCraftLauncher#17]
### Is this request related to a bug?

Theres some bug too. Siging in a account dosent send me a code in my gmail.

### Describe the request.

I dont have a microsoft account. 

### Anything else?

No problem..

**Comment by SolDev69** [comment]
Will not be fixed. Buy Minecraft.

**Comment by Rocraft27** [comment]
Soldev, im not old enough!

**Comment by SolDev69** [comment]
I got Java Edition for my 11th birthday, ask your parents for it or something,

**Comment by Rocraft27** [comment]
Please... please add offline button.
