### ISSUE TITLE
Fine...

### ISSUE THREAD

**Issue by Rocraft27** [SolDev69/SolCraftLauncher#20]
### Is this request related to a bug?

Nope

### Describe the request.

Without the offline button, without a account, can i still play, when they hit play, and something will show up that is gonna require a display name to type to play.

### Anything else?

Or add offline button.

**Comment by SolDev69** [comment]
No. I will not support piracy. Buy the game.

**Comment by Marshall2439** [comment]
Buy minecraft dumbass
