### ISSUE TITLE
Add Offline account 

### ISSUE THREAD

**Issue by Isokaz** [SolDev69/SolCraftLauncher#21]
### Describe the request.

Add an Offline account,because i don't have any copy of original Minecraft

**Comment by SolDev69** [comment]
I will not support piracy.

**Comment by Vincent392** [comment]
> I will not support piracy.

agreed.

However maybe add offline mode to official accounts.

**Comment by SolDev69** [comment]
If you log in to a Microsoft account you can use that account offline, if you mean something like how MMC an PrismLauncher do it where you can add offline acc if you're already logged in, I might add that in the future.

**Comment by Isokaz** [comment]
> > I will not support piracy.
> 
> agreed.
> 
> However maybe add offline mode to official accounts.

that is what I mean

**Comment by Vincent392** [comment]
> If you log in to a Microsoft account you can use that account offline, if you mean something like how MMC an PrismLauncher do it where you can add offline acc if you're already logged in, I might add that in the future.

more or less what I was saying
