### ISSUE TITLE
[BUG] <Sign in error>

### ISSUE THREAD

**Issue by PegNattha** [SolDev69/SolCraftLauncher#23]
### Describe the bug

![Screenshot_20240624-162012_SolCraftLauncher (SolDev PojavLancher fork)](https://github.com/SolDev69/SolCraftLauncher/assets/131944266/7b36eef0-dd4e-4b1d-b112-9af7a52ec406)

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

-

### Platform

```markdown
Sol version
```

### Anything else?

Can you add a free login?

**Comment by SolDev69** [comment]
You don't own MC. SCL currently doesn't have demo mode support.

**Comment by SolDev69** [comment]
this is gonna be mojang issue not scl, auth servers keep dying
